### PR TITLE
filter by not found, search link for not found

### PR DESCRIPTION
**Pull request by pursual**
Filter to only not found albums. TODO, hide this filter when not yet connected to spotify. For now it is hidden until albums are found.

### CODE REVIEW

**Comment by pursual** [comment]
Added link to search spotify for not found albums.

**Comment by metric152** [comment]
Looks like my IDE made tabs instead of spaces. Cleaned that up and pushed the changes.
On library.html:2 can you use albums().total and ng-if instead?
Also move the hr in-between the divs.

In library.js can you add a function called changeFilter and move the code from the controller there and add a reference to the this var to the function?

Thanks for adding this feature.

**Comment by pursual** [comment]
Made those tweaks. Probably have whitespace conflicts now. Would be nice to set up some communication from library to root in order to move the filterbox to the fixed div. Maybe put the var "onlyNotFound" on root scope and do a watch on it from the library directive.

**Comment by metric152** [comment]
Sorry I didn't respond quicker. I got busy with some stuff at home. I'll merge these changes in tomorrow morning. 

Thanks for taking care of this feature.

**Comment by metric152** [comment]
I've refactored quite a bit of code and moved a lot of functionality to a service library. I added your filter code.

**Pull request closed without merging**
